---
title: "/dev/loki"
baseURL: "https://loki.dev/"
# theme: "zen"
# theme: "hugo-theme-minos"
theme: "hugo-notepadium"
languageCode: "de"
defaultContentLanguage: "en"
pluralizeListtitles: false
removePathAccents: true 
paginate: 10 
paginatePath: "page"
rssLimit: 20
author:
  name: "Torsten Zielke"
  url: "https://loki.dev/"
params:
  contact: "torsten.zielke@protonmail.com"
  copyright: "This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/)"
  description: "Just another devlog."
  slogan: '"Talk is cheap. Show me the code!" - L. Torvalds'
  style: dark
  dateFormat: "2006-01-02 15:04"
  nav:
    showCategories: true
    showTags: true
    custom:
      - title: "whoami"
        url: "/whoami"
      - title: "impressum"
        url: "/impressum"
